export const PRODUCTS_DATA = [
  {
    id: "1",
    name: "Wireless Headphones Pro",
    slug: "wireless-headphones-pro",
    category: "Consumer Electronics",
    categorySlug: "consumer-electronics",
    price: 1299.99,
    originalPrice: 1999.99,
    description:
      "Premium wireless headphones with active noise cancellation, 30-hour battery life, and premium sound quality. Perfect for professionals and audiophiles.",
    images: [
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
    ],
    rating: 4.8,
    reviews: [
      {
        author: "Sarah M.",
        title: "Excellent sound quality!",
        comment: "Excellent sound quality and comfort!",
        rating: 5,
        id: "1",
        date: "2025-01-10",
        helpful: 12,
      },
      {
        author: "John D.",
        title: "Great battery life",
        comment: "Great battery life, highly recommended.",
        rating: 5,
        id: "2",
        date: "2025-01-09",
        helpful: 8,
      },
      {
        author: "Alex T.",
        title: "Very comfortable",
        comment: "Very comfortable for long listening sessions.",
        rating: 4,
        id: "3",
        date: "2025-01-08",
        helpful: 5,
      },
    ],
    stock: 25,
    badge: "Hot Deal",
    specifications: {
      "Noise Cancellation": "Active (ANC)",
      "Battery Life": "30 hours",
      Connectivity: "Bluetooth 5.0",
      Weight: "250g",
      Colors: "Black, Silver, Gold",
    },
  },
  {
    id: "2",
    name: "Smart Watch Pro",
    slug: "smart-watch-pro",
    category: "Consumer Electronics",
    categorySlug: "consumer-electronics",
    price: 2999.99,
    originalPrice: 4999.99,
    description:
      "Advanced smartwatch with health tracking, GPS, and 7-day battery life. Monitor your fitness and stay connected.",
    images: [
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
    ],
    rating: 4.6,
    reviews: [
      { author: "Emma W.", text: "Amazing fitness tracking capabilities!", rating: 5 },
      { author: "Mike K.", text: "Battery life is impressive.", rating: 4 },
    ],
    stock: 15,
    badge: "New",
    specifications: {
      Display: "AMOLED 1.4 inch",
      Battery: "7 days",
      "Health Tracking": "Heart rate, Sleep, Steps, Calories",
      "Water Resistance": "5ATM",
      Colors: "Black, Blue, Red",
    },
  },
  {
    id: "3",
    name: "Premium Phone Case Bundle",
    slug: "premium-phone-case-bundle",
    category: "Consumer Electronics",
    categorySlug: "consumer-electronics",
    price: 299.99,
    originalPrice: 799.99,
    description:
      "Set of 3 premium phone cases with screen protectors and cleaning cloth. Protect your device in style.",
    images: [
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
    ],
    rating: 4.4,
    reviews: [{ author: "Lisa R.", text: "Great value for money!", rating: 4 }],
    stock: 50,
    badge: "Popular",
    specifications: {
      Material: "TPU + PC",
      Compatibility: "iPhone/Samsung",
      Package: "3 cases + 6 protectors",
      "Color Options": "Black, Blue, Red",
    },
  },
  {
    id: "4",
    name: "USB-C Cable 3m",
    slug: "usb-c-cable-3m",
    category: "Consumer Electronics",
    categorySlug: "consumer-electronics",
    price: 149.99,
    originalPrice: 399.99,
    description: "High-speed USB-C cable with fast charging capability. 3-meter length for convenience.",
    images: [
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
    ],
    rating: 4.5,
    reviews: [{ author: "Tom B.", text: "Durable and reliable.", rating: 5 }],
    stock: 100,
    badge: "Best Seller",
    specifications: {
      Length: "3 meters",
      "Max Current": "5A",
      "Data Speed": "480 Mbps",
      Warranty: "2 years",
    },
  },
  {
    id: "5",
    name: "Portable Charger 20000mAh",
    slug: "portable-charger-20000mah",
    category: "Consumer Electronics",
    categorySlug: "consumer-electronics",
    price: 399.99,
    originalPrice: 999.99,
    description: "High-capacity portable power bank with fast charging. Charge multiple devices simultaneously.",
    images: [
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
    ],
    rating: 4.7,
    reviews: [{ author: "Rachel C.", text: "Excellent power capacity!", rating: 5 }],
    stock: 30,
    badge: "Hot Deal",
    specifications: {
      Capacity: "20000 mAh",
      "Charging Ports": "3 USB ports",
      "Fast Charging": "18W",
      Weight: "350g",
    },
  },
  {
    id: "6",
    name: "Bluetooth Speaker Compact",
    slug: "bluetooth-speaker-compact",
    category: "Consumer Electronics",
    categorySlug: "consumer-electronics",
    price: 599.99,
    originalPrice: 1299.99,
    description: "Compact wireless speaker with superior sound quality, waterproof design, and 12-hour battery life.",
    images: [
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
    ],
    rating: 4.5,
    reviews: [
      {
        author: "Chris L.",
        title: "Great sound",
        comment: "Amazing sound for a compact speaker!",
        rating: 5,
        id: "1",
        date: "2025-01-15",
        helpful: 10,
      },
    ],
    stock: 20,
    badge: "New",
    specifications: {
      "Speaker Size": "8 inches",
      "Battery Life": "12 hours",
      "Water Resistance": "IPX6",
      Connectivity: "Bluetooth 5.0",
      Weight: "400g",
    },
  },
  {
    id: "7",
    name: "Wireless Charging Pad",
    slug: "wireless-charging-pad",
    category: "Consumer Electronics",
    categorySlug: "consumer-electronics",
    price: 299.99,
    originalPrice: 799.99,
    description: "Fast wireless charging pad compatible with all Qi-enabled devices. Sleek minimalist design.",
    images: [
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
    ],
    rating: 4.6,
    reviews: [
      {
        author: "Diana P.",
        title: "Perfect design",
        comment: "Elegant and works perfectly!",
        rating: 5,
        id: "1",
        date: "2025-01-14",
        helpful: 8,
      },
    ],
    stock: 35,
    badge: "New",
    specifications: {
      "Charging Speed": "15W",
      Compatibility: "Qi-enabled devices",
      Materials: "Aluminum + Rubber",
      Colors: "Black, White, Gray",
    },
  },
  {
    id: "8",
    name: "USB Hub 7-Port",
    slug: "usb-hub-7-port",
    category: "Consumer Electronics",
    categorySlug: "consumer-electronics",
    price: 449.99,
    originalPrice: 1199.99,
    description: "High-speed USB 3.0 hub with 7 ports and individual switches. Perfect for productivity.",
    images: [
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
    ],
    rating: 4.7,
    reviews: [
      {
        author: "Marcus J.",
        title: "Very useful",
        comment: "Great for my desk setup!",
        rating: 5,
        id: "1",
        date: "2025-01-13",
        helpful: 12,
      },
    ],
    stock: 18,
    badge: "New",
    specifications: {
      Ports: "7x USB 3.0",
      "Data Speed": "5 Gbps",
      "Power Delivery": "2.4A per port",
      Material: "Aluminum",
    },
  },
  {
    id: "9",
    name: "Laptop Stand Pro",
    slug: "laptop-stand-pro",
    category: "Consumer Electronics",
    categorySlug: "consumer-electronics",
    price: 349.99,
    originalPrice: 899.99,
    description: "Adjustable aluminum laptop stand for better ergonomics and cooling. Supports up to 17 inches.",
    images: [
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
    ],
    rating: 4.8,
    reviews: [
      {
        author: "Olivia K.",
        title: "Excellent build",
        comment: "Very sturdy and well-designed!",
        rating: 5,
        id: "1",
        date: "2025-01-12",
        helpful: 15,
      },
    ],
    stock: 25,
    badge: "New",
    specifications: {
      Material: "Aluminum Alloy",
      "Max Width": "17 inches",
      "Max Load": "15kg",
      "Height Range": "10-40cm",
      Colors: "Silver, Space Gray",
    },
  },
  {
    id: "10",
    name: "Mechanical Keyboard RGB",
    slug: "mechanical-keyboard-rgb",
    category: "Consumer Electronics",
    categorySlug: "consumer-electronics",
    price: 699.99,
    originalPrice: 1699.99,
    description: "Premium mechanical keyboard with RGB lighting, programmable keys, and hot-swap switches.",
    images: [
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
      "https://i.postimg.cc/Y9KZwRzs/Gemini-Generated-Image-mme3rsmme3rsmme3.png",
    ],
    rating: 4.9,
    reviews: [
      {
        author: "Kevin W.",
        title: "Best keyboard ever",
        comment: "Amazing typing feel and lights!",
        rating: 5,
        id: "1",
        date: "2025-01-11",
        helpful: 20,
      },
    ],
    stock: 12,
    badge: "New",
    specifications: {
      "Switch Type": "Cherry MX Hot-Swap",
      Layout: "Full 104-key",
      Lighting: "RGB per-key",
      Connectivity: "Wireless 2.4GHz",
      Material: "Aluminum + PBT",
    },
  },
]
